<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#testconnection_span');
        jQuery('#test_credentials').click(function () {

            var subdomain = jQuery('#wesupply_api_step_2_wesupply_subdomain').val();
            var apiClientId = jQuery('#wesupply_api_step_1_wesupply_client_id').val();
            var apiClientSecret = jQuery('#wesupply_api_step_1_wesupply_client_secret').val();

            var params = {'subdomain':subdomain, 'apiClientId':apiClientId, 'apiClientSecret': apiClientSecret};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#valid_message_span').text('');
                    jQuery('#invalid_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();

                    if (response.status > 200) {
                        jQuery('#invalid_message_span').text('Something went wrong.');
                    } else {

                        if(response.responseJSON.success === false){
                            jQuery('#invalid_message_span').text(response.responseJSON.message);
                        }else{
                            collectSpan.find('.collected').show();
                            jQuery('#valid_message_span').text(response.responseJSON.message)
                        }
                    }

                }

            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="testconnection_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="valid_message_span"></span><span style="color:red" id="invalid_message_span"></span>
</span>