<div class="not-found">
    <h1><?= $this->getPageTitle(); ?> <?= /* @escapeNotVerified */ __('page was not found') ?></h1>
    <div class="message">
        <p><?= /* @escapeNotVerified */ __('If you typed the URL directly, please make sure the spelling is correct.') ?></p>
        <p><?= /* @escapeNotVerified */ __('If you clicked on a link to get here, the link is outdated.') ?></p>
    </div>
</div>